services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "3001"
    volumes:
      - ./logs:/usr/src/app/nginx_logs

  waf:
    build: ./nginx
    container_name: waf
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - MODSEC_AUDIT_ENGINE=On
      # We keep this pointing to stdout to confirm blocks in the main log,
      # but we will now parse the error.log file.
      - MODSEC_AUDIT_LOG=/dev/stdout
    depends_on:
      - backend

